spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG

